services:
  - type: web
    name: aure-sanchez
    env: node
    buildCommand: npm install
    startCommand: |
      echo "Starting servers..."
      npm start
    envVars:
      - key: PORT
        value: 10000