services:
  - type: web
    name: aure-sanchez
    env: node
    buildCommand: |
      if [ -f "build.sh" ]; then
        bash build.sh
      else
        npm install
        npm run build
        mkdir -p dist
        cp -r build/* dist/ || true
        ls -la dist/
      fi
    startCommand: |
      echo "Current directory: $(pwd)"
      ls -la
      NODE_ENV=production node src/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000