services:
  - type: web
    name: aure-sanchez
    env: node
    buildCommand: npm install && npm run build
    startCommand: node src/server/server.js
    envVars:
      - key: NODE_ENV
        value: production